#!/bin/sh
if [ -z "$1" ]
then
  echo "Which folder do you want to deploy to GitHub Pages?"
  exit 1
fi
git add .
if [ -z "$2"]
then
  git commit -m "push to ghpages"
else
  git commit -m "$2"
fi
git subtree push --prefix $1 origin gh-pages